apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarkus-knative
spec:
  runLatest: 
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhsummit/greeter:0.0.1